image: node:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: fiddle_test
  POSTGRES_USER: fiddle
  POSTGRES_PASSWORD: fiddle
  NODE_ENV: ci

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm test

lint:
  stage: test
  script: npm run lint

docker_build:
  stage: build
  image: docker.latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t registry.gitlab.com/nearprotocol/near-fiddle-api:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/nearprotocol/near-fiddle-api:$CI_COMMIT_TAG
  only:
    - tags
