image: node:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: fiddle_test
  POSTGRES_USER: fiddle
  POSTGRES_PASSWORD: fiddle
  NODE_ENV: ci

stages:
  - test


test_with_lab:
  stage: test
  script: yarn && yarn test

lint:
  stage: test
  script: yarn && yarn lint
