language: node_js
node_js:
 - "lts/*"
services:
  - postgresql
before_script:
  - psql -c "create user fiddle with encrypted password 'fiddle';" -U postgres
  - psql -c "create database fiddle_test;" -U postgres
  - psql -c "grant all privileges on database fiddle_test to fiddle" -U postgres
